from typing import Optional

WORLD_NAME_MAX_LENGTH = 100
WORLD_DESCRIPTION_MAX_LENGTH = 1000
ROOM_NAME_MAX_LENGTH = 100
ROOM_DESCRIPTION_MAX_LENGTH = 1000
EXIT_NAME_MAX_LENGTH = 100
EXIT_DESCRIPTION_MAX_LENGTH = 1000
ITEM_NAME_MAX_LENGTH = 100
ITEM_DESCRIPTION_MAX_LENGTH = 1000
USER_NAME_MAX_LENGTH = 20
EMAIL_MAX_LENGTH = 1000
USER_ID_MAX_LENGTH = 1000
SOCIAL_INTERACTION_MAX_LENGTH = 1000

WORLDS_PER_USER_MAX = 10
TEMPLATES_PER_USER_MAX = 10
ROOMS_PER_WORLD_MAX: Optional[str] = None
ITEMS_PER_WORLD_MAX: Optional[str] = None
EXITS_PER_WORLD_MAX: Optional[str] = None
ITEMS_PER_ROOM_MAX: Optional[str] = None
EXITS_PER_ROOM_MAX: Optional[str] = None
