services:
  architext-backend:
    build: 
      context: .
      dockerfile: ./server/architext/entrypoints/socketio/Dockerfile
    restart: always
    expose:
     - "5000"
    # volumes:
    #   - ./volumes/architext/logs:/usr/src/app/logs
    #   - ./server/en_config.yml:/usr/src/app/config.yml
    env_file:
      - server/.env

  architext-web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    restart: always
    expose:
      - "3000"
    env_file:
      - web/.env.local

  architext-db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./volumes/db_data:/var/lib/postgresql/data
      # to backup the database, run:
      # docker exec -t architext-db-1 pg_dumpall -U postgres > backup.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

