"""empty message

Revision ID: 2994a1147f4d
Revises: f859ee70ed88
Create Date: 2025-05-19 12:55:53.357734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2994a1147f4d'
down_revision: Union[str, None] = 'f859ee70ed88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rooms_world_id_fkey', 'rooms', type_='foreignkey')
    op.create_foreign_key(None, 'rooms', 'worlds', ['world_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('users_world_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'worlds', ['world_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_world_id_fkey', 'users', 'worlds', ['world_id'], ['id'])
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.create_foreign_key('rooms_world_id_fkey', 'rooms', 'worlds', ['world_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
