"""empty message

Revision ID: 8addc3339f70
Revises: 2994a1147f4d
Create Date: 2025-05-19 13:00:33.903210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8addc3339f70'
down_revision: Union[str, None] = '2994a1147f4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exits_room_id_fkey', 'exits', type_='foreignkey')
    op.drop_constraint('exits_destination_room_id_fkey', 'exits', type_='foreignkey')
    op.create_foreign_key(None, 'exits', 'rooms', ['destination_room_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'exits', 'rooms', ['room_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('items_room_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'rooms', ['room_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('users_world_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'worlds', ['world_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('worlds_base_template_id_fkey', 'worlds', type_='foreignkey')
    op.create_foreign_key(None, 'worlds', 'world_templates', ['base_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worlds', type_='foreignkey')
    op.create_foreign_key('worlds_base_template_id_fkey', 'worlds', 'world_templates', ['base_template_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_world_id_fkey', 'users', 'worlds', ['world_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_room_id_fkey', 'items', 'rooms', ['room_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'exits', type_='foreignkey')
    op.drop_constraint(None, 'exits', type_='foreignkey')
    op.create_foreign_key('exits_destination_room_id_fkey', 'exits', 'rooms', ['destination_room_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('exits_room_id_fkey', 'exits', 'rooms', ['room_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
