"""empty message

Revision ID: f859ee70ed88
Revises: 
Create Date: 2025-05-19 12:49:57.039362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f859ee70ed88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('world_visit_records_world_id_fkey', 'world_visit_records', type_='foreignkey')
    op.create_foreign_key(None, 'world_visit_records', 'worlds', ['world_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'world_visit_records', type_='foreignkey')  # type: ignore
    op.create_foreign_key('world_visit_records_world_id_fkey', 'world_visit_records', 'worlds', ['world_id'], ['id'])
    # ### end Alembic commands ###
